# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78362790f2b2062d39346fe59632c91bcd6690b281f86d8b2ef1cc61c81b7b5cf66cd5baf5f378bda82b39c03d4fdb4e5abf27070d5e3ab8ca761db83e362935

test:
  secret_key_base: 97c37317bdea1914fb79af66c0271caed4113a3b0c486f9d3b7e8a1711b339721554caf9b6475a9fd18b419f6c6d57898a292ff2f170321cf42080797bb4a08c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
